namespace ObiOne.DomainRepositoryPattern.Specialized.DI.Infra {
    public enum EnLanguage {
        Hebrew = 1,
        Spanish_Ar = 2,
        English = 3,
        Polish = 5,
        English_Sg = 6,
        Spanish_Pa = 7,
        English_Gb = 8,
        German = 9,
        Serbian = 10,
        Danish = 11,
        Norwegian = 12,
        Italian = 13,
        Hungarian = 14,
        Chinese = 15,
        Dutch = 16,
        Finnish = 17,
        Greek = 18,
        Portuguese = 19,
        Swedish = 20,
        English_Cy = 21,
        French = 22,
        Spanish = 23,
        Russian = 24,
        Spanish_La = 25,
        Czech_Cz = 26,
        Slovak_Sk = 27,
        Korean_Kr = 28,
        Portuguese_Br = 29,
        Japanese_Jp = 30,
        Turkish_Tr = 31,
        Arabic = 32,
        TrdtnlChinese_Hk = 35,
    }
}
